### ISSUE TITLE
Feature: Rowdy Gaol

### ISSUE THREAD

**Issue by Frosk-Kristian** [carlst99/UVOCBot#18]
Add functionality to the bot enabling people to use the command '!bonk <username>' and send them to a channel '#rowdy-gaol'.
EDIT: and play this sound https://www.youtube.com/watch?v=c4wopc9-SJU&ab_channel=AviatorAlex1

**Comment by carlst99** [comment]
In order to make this more flexible, I'll let the user select a voice channel instead of hard-coding #rowdy-gaol.

Will begin implementing this tonight.

**Comment by carlst99** [comment]
Implemented and merged with #20
